server:
  port: 9000

spring:
  application:
    name: service0
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/distributed-database-service0?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: ab215687DA.
      initial-size: 5 # 初始化连接大小
      max-active: 20 # 最大连接池数量
      min-idle: 5 # 最小连接池数量
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: false # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20 # 开启poolPreparedStatements后生效
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 600000 # 配置一个连接在池中最小生存的时间，单位是毫秒,必须比配置大最小值大
      validation-query: SELECT 1 FROM DUAL # 测试连接
      # validation-query-timeout: 5000
      test-on-borrow: false # 获取连接时执行检测，建议关闭，影响性能
      test-on-return: false # 归还连接时执行检测，建议关闭，影响性能
      test-while-idle: true # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
      filters: stat,wall # 配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # druid监控页面，账号和密码都在配置类代码中配置

mybatis-plus:
  global-config:
    enable-sql-runner: true
  mapper-locations: classpath:/mapper/*.xml
  configuration: #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        # 暴漏的接口 - 所有接口
        include: "*"
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
bt:
  enable: true
  paths:
    - /test
    - /feign/api/service0/book/addBooks
    - /feign/api/service0/book/deleteBook
    - /feign//api/service0/book/addBook
    - /feign//api/service0/book/multiUpdate
  rollback-port: 9091
  host: localhost